#!/usr/bin/env python3
"""更新 ``final_v0`` 文件树索引。

Update the complete file-tree index for ``final_v0``.

该工具只读取 ``final_v0`` 并只写入同目录下的 ``FINAL_V0_TREE.md``。
The tool reads only ``final_v0`` and writes only ``FINAL_V0_TREE.md`` there.
"""

from __future__ import annotations

import hashlib
from pathlib import Path


FINAL_ROOT = Path(__file__).resolve().parents[1]
INDEX_PATH = FINAL_ROOT / "FINAL_V0_TREE.md"


# 中文和英文说明共同维护，避免文件树只有名称而缺少职责信息。
# Chinese and English descriptions are maintained together so every file has a clear role.
EXACT_DESCRIPTIONS: dict[str, str] = {
    "README.md": "收尾工作区入口、写入边界与自动更新规则 / Workspace entry, write boundary, and synchronization rules.",
    "FINAL_V0_TREE.md": "本目录完整树状结构、逐文件说明和完整性校验 / Complete tree, per-file descriptions, and integrity checks.",
    "records/WORK_LOG.md": "逻辑工作操作、状态、证据与验证记录 / Logical operations, status, evidence, and verification log.",
    "records/SCAN_PROTOCOL.md": "逐字节扫描、输入头部扫描、输出映射及安全规则 / Byte-level scan, input-head scan, output mapping, and safety rules.",
    "records/PENDING_AGENT_UPDATES.md": "等待用户要求后再整理或录入 `_agent` 的候选草稿 / Candidate `_agent` updates held until explicitly requested.",
    "algorithm_diagrams/README.md": "算法图示格式、证据和维护标准 / Diagram format, evidence, and maintenance standard.",
    "tools/update_final_v0_index.py": "自动重建 final_v0 文件树和逐文件校验信息 / Rebuild the final_v0 tree and per-file integrity data.",
}


def sha256_file(path: Path) -> str:
    """逐块读取文件并返回 SHA-256；stream a file and return its SHA-256 digest."""

    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def generic_description(relative_path: str) -> str:
    """为自动生成文件提供保守说明；provide a conservative description for generated files."""

    suffix = Path(relative_path).suffix.lower()
    if relative_path.startswith("algorithm_diagrams/"):
        return "算法流程或脚本结构图及其证据说明 / Algorithm or script-structure diagram with evidence notes."
    if relative_path.startswith("records/generated/"):
        return "由审计工具生成的机器可读扫描证据 / Machine-readable scan evidence generated by audit tooling."
    if relative_path.startswith("records/"):
        return "项目收尾审计记录或报告 / Project-finalization audit record or report."
    if relative_path.startswith("tools/") and suffix == ".py":
        return "带中英文注释的收尾审计工具 / Finalization audit tool with bilingual documentation."
    return "收尾交付文件；详细职责见文件正文 / Finalization deliverable; see the file body for its detailed role."


def build_tree(relative_files: list[str]) -> list[str]:
    """构建稳定排序的 Markdown 树；build a deterministically sorted Markdown tree."""

    tree: dict[str, dict] = {}
    for relative_path in relative_files:
        node = tree
        for part in Path(relative_path).parts:
            node = node.setdefault(part, {})

    lines = ["final_v0/"]

    def visit(node: dict[str, dict], prefix: str) -> None:
        names = sorted(node, key=lambda name: (not bool(node[name]), name.lower()))
        for index, name in enumerate(names):
            last = index == len(names) - 1
            connector = "└── " if last else "├── "
            lines.append(f"{prefix}{connector}{name}")
            if node[name]:
                visit(node[name], prefix + ("    " if last else "│   "))

    visit(tree, "")
    return lines


def render_index() -> str:
    """生成索引正文；render the complete index document."""

    files = sorted(
        path for path in FINAL_ROOT.rglob("*") if path.is_file() and path != INDEX_PATH
    )
    relative_files = [path.relative_to(FINAL_ROOT).as_posix() for path in files]
    # 索引必须把自身也列入树中，但其摘要不参与自引用哈希。
    # The index lists itself, while intentionally omitting a self-referential digest.
    all_tree_files = sorted(relative_files + [INDEX_PATH.name])

    lines = [
        "# `final_v0` 文件树与逐文件说明 / File Tree and Per-file Descriptions",
        "",
        "> 本文件由 `tools/update_final_v0_index.py` 自动生成。索引文件自身不记录 SHA-256，以避免自引用导致校验值永远变化。",
        "",
        "## 树状结构 / Tree",
        "",
        "```text",
        *build_tree(all_tree_files),
        "```",
        "",
        "## 逐文件说明与完整性 / Per-file descriptions and integrity",
        "",
        "| 文件 / File | 字节 / Bytes | SHA-256 | 详细说明 / Detailed description |",
        "|---|---:|---|---|",
    ]

    for path, relative_path in zip(files, relative_files):
        description = EXACT_DESCRIPTIONS.get(relative_path, generic_description(relative_path))
        lines.append(
            f"| `{relative_path}` | {path.stat().st_size} | `{sha256_file(path)}` | {description} |"
        )
    lines.append(
        "| `FINAL_V0_TREE.md` | self | intentionally omitted | 本文件自身 / This index itself. |"
    )
    lines.extend(
        [
            "",
            "## 完整性规则 / Integrity rule",
            "",
            f"- 永久文件总数（含本索引）/ Permanent file count including this index: **{len(all_tree_files)}**。",
            "- 每次新增、修改或删除业务文件后运行索引工具；索引同步本身不递归形成新日志项。",
            "- A missing hash means the file was not successfully indexed and must be treated as unverified.",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> None:
    """仅更新 final_v0 索引；update only the final_v0 index."""

    INDEX_PATH.write_text(render_index(), encoding="utf-8", newline="\n")


if __name__ == "__main__":
    main()

